services:
  # app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   volumes:
  #     - .:/home/node/app
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: root
    expose:
      - 5431
    ports:
      - 5431:5432 # Host:Container
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - .docker/postgres/data:/var/lib/postgresql/data