GET http://localhost:3000/bank-accounts


### 

GET http://localhost:3000/bank-accounts/5adf6254-fe68-4f19-9f25-5321ec485b2f


###

POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "accountNumber": "123456",
  "ownerName": "John Doe"
}